VALID_HORSES = {
    "Admire Vega",
    "Agnes Tachyon",
    "Air Groove",
    "Air Messiah",
    "Air Shakur",
    "Almond Eye",
    "Aston Machan",
    "Bamboo Memory",
    "Believe",
    "Biko Pegasus",
    "Biwa Hayahide",
    "Cheval Grand",
    "Copano Rickey",
    "Curren Bouquetd'or",
    "Curren Chan",
    "Daiichi Ruby",
    "Daitaku Helios",
    "Daiwa Scarlet",
    "Dantsu Flame",
    "Daring Heart",
    "Daring Tact",
    "Dream Journey",
    "Duramente",
    "El Condor Pasa",
    "Eishin Flash",
    "Espoir City",
    "Fenomeno",
    "Fine Motion",
    "Furioso",
    "Fusaichi Pandora",
    "Fuji Kiseki",
    "Gentildonna",
    "Gold City",
    "Gold Ship",
    "Gran Alegria",
    "Grass Wonder",
    "Haru Urara",
    "Hishi Akebono",
    "Hishi Amazon",
    "Hishi Miracle",
    "Hokko Tarumae",
    "Ikuno Dictus",
    "Inari One",
    "Ines Fujin",
    "Jungle Pocket",
    "K.S.Miracle",
    "Kawakami Princess",
    "Katsuragi Ace",
    "Kitasan Black",
    "King Halo",
    "Loves Only You",
    "Lucky Lilac",
    "Manhattan Cafe",
    "Marvelous Sunday",
    "Maruzensky",
    "Matikanefukukitaru",
    "Matikanetannhauser",
    "Mayano Top Gun",
    "Meisho Doto",
    "Mejiro Ardan",
    "Mejiro Bright",
    "Mejiro Dober",
    "Mejiro McQueen",
    "Mejiro Palmer",
    "Mejiro Ramonu",
    "Mejiro Ryan",
    "Mihono Bourbon",
    "Mr. C.B.",
    "Nakayama Festa",
    "Narita Brian",
    "Narita Taishin",
    "Narita Top Road",
    "Neo Universe",
    "Nice Nature",
    "Nishino Flower",
    "No Reason",
    "North Flight",
    "Oguri Cap",
    "Orfevre",
    "Red Desire",
    "Rhein Kraft",
    "Rice Shower",
    "Royce and Royce",
    "Sakura Bakushin O",
    "Sakura Chiyono O",
    "Sakura Chitose O",
    "Sakura Laurel",
    "Satono Crown",
    "Satono Diamond",
    "Seeking the Pearl",
    "Seiun Sky",
    "Shinko Windy",
    "Shirley Sky",
    "Silence Suzuka",
    "Sirius Symboli",
    "Smart Falcon",
    "Sounds of Earth",
    "Special Week",
    "Stay Gold",
    "Still in Love",
    "Sun Visor",
    "Super Creek",
    "Sweep Tosho",
    "Symboli Kris S",
    "Symboli Rudolf",
    "T.M. Opera O",
    "Taiki Shuttle",
    "Tamamo Cross",
    "Tanino Gimlet",
    "Tap Dance City",
    "Tosen Jordan",
    "Tokai Teio",
    "Transcend",
    "Tsurumaru Tsuyoshi",
    "Twin Turbo",
    "Verxina",
    "Vivlos",
    "Vodka",
    "Win Variation",
    "Winning Ticket",
    "Wonder Acute",
    "Yaeno Muteki",
    "Yamanin Zephyr",
    "Yukino Bijin",
    "Zenno Rob Roy",
}
